import type { StudioAppBootstrap } from '../../src/shared/hackathon-contracts';
import { bootstrapFixture } from './fixtures';

const NOW_DATE = new Date();
const NOW = NOW_DATE.toISOString();

function daysFromNow(days: number): string {
  return new Date(NOW_DATE.valueOf() + days * 86_400_000).toISOString();
}

function dateOnly(value: string): string {
  return value.slice(0, 10);
}

const DEADLINE_72_HOURS = daysFromNow(2);
const DEADLINE_14_DAYS = daysFromNow(10);
const DEADLINE_30_DAYS = daysFromNow(28);

export function hackathonBootstrapFixture(): StudioAppBootstrap {
  const founder = bootstrapFixture();
  const hackathonNarrative = {
    ...founder.narrativeProfiles.find((item) => item.id === 'narrative:test:draft')!,
    id: 'narrative:test:hackathon',
    approvalState: 'approved' as const,
    contentSha256: 'f'.repeat(64),
    approvedAt: NOW,
  };
  const mediaVenture = {
    id: 'venture:media',
    legalEntityId: 'legal-entity:test',
    name: '555stream',
    category: 'Human and agent media runtime',
    utility: 'Turns useful human and agent work into live media and sponsor experiences.',
    stage: 'pre_production' as const,
    status: 'active' as const,
    publicUrl: null,
    defaultNarrativeProfileId: null,
    currentDemoVersionId: 'demo-version:test:2',
  };

  return {
    ...founder,
    ventures: [...founder.ventures, mediaVenture],
    narrativeProfiles: [...founder.narrativeProfiles, hackathonNarrative],
    organizations: [
      {
        id: 'organization:ethglobal',
        name: 'ETHGlobal',
        normalizedName: 'ethglobal',
        kind: 'protocol',
        website: 'https://ethglobal.com',
        description: 'Ethereum developer events and hackathons.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'organization:bnb',
        name: 'BNB Chain',
        normalizedName: 'bnb chain',
        kind: 'protocol',
        website: 'https://bnbchain.org',
        description: 'BNB Chain ecosystem programs.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'organization:agentic-cinema',
        name: 'Agentic Cinema',
        normalizedName: 'agentic cinema',
        kind: 'company',
        website: null,
        description: 'Agentic media build competition.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'organization:colosseum',
        name: 'Colosseum',
        normalizedName: 'colosseum',
        kind: 'accelerator',
        website: 'https://colosseum.com',
        description: 'Always-on Solana startup and hackathon pathway.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    opportunities: [
      {
        id: 'opportunity:ethglobal-agentic',
        organizerOrganizationId: 'organization:ethglobal',
        name: 'ETHGlobal Agentic Ethereum',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://ethglobal.com/events',
        applicationUrl: 'https://ethglobal.com/events',
        openDate: dateOnly(NOW),
        deadline: dateOnly(DEADLINE_30_DAYS),
        startDate: dateOnly(daysFromNow(20)),
        endDate: dateOnly(DEADLINE_30_DAYS),
        format: 'online',
        location: null,
        eligibilitySummary: 'Open online build competition.',
        termsSummary: 'Use sponsor technology honestly and disclose prior work.',
        capitalPrizeSummary: 'Sponsor bounties and ecosystem follow-on opportunities.',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'opportunity:bnb-online',
        organizerOrganizationId: 'organization:bnb',
        name: 'BNB Hack Online',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://bnbchain.org',
        applicationUrl: 'https://bnbchain.org',
        openDate: dateOnly(NOW),
        deadline: dateOnly(DEADLINE_72_HOURS),
        startDate: dateOnly(NOW),
        endDate: dateOnly(DEADLINE_72_HOURS),
        format: 'online',
        location: null,
        eligibilitySummary: 'Online ecosystem build competition.',
        termsSummary: 'Use BNB technology in the submitted adapter.',
        capitalPrizeSummary: 'Prize and ecosystem support.',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'opportunity:agentic-cinema',
        organizerOrganizationId: 'organization:agentic-cinema',
        name: 'Agentic Cinema',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: null,
        applicationUrl: null,
        openDate: dateOnly(NOW),
        deadline: dateOnly(DEADLINE_14_DAYS),
        startDate: dateOnly(NOW),
        endDate: dateOnly(DEADLINE_14_DAYS),
        format: 'online',
        location: null,
        eligibilitySummary: 'Agentic media build competition.',
        termsSummary: null,
        capitalPrizeSummary: null,
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'opportunity:colosseum-eternal',
        organizerOrganizationId: 'organization:colosseum',
        name: 'Colosseum Eternal',
        opportunityType: 'hackathon',
        status: 'rolling',
        publicUrl: 'https://colosseum.com/eternal',
        applicationUrl: 'https://colosseum.com/eternal',
        openDate: null,
        deadline: null,
        startDate: null,
        endDate: null,
        format: 'online',
        location: null,
        eligibilitySummary: 'Rolling Solana startup build pathway.',
        termsSummary: 'A new four-week build begins when the founder starts an entry.',
        capitalPrizeSummary: 'Accelerator and pre-seed consideration.',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    hackathonCycles: [
      {
        id: 'cycle:ethglobal-agentic',
        opportunityId: 'opportunity:ethglobal-agentic',
        cycleName: 'ETHGlobal Agentic Ethereum',
        registrationOpenAt: NOW,
        registrationCloseAt: DEADLINE_30_DAYS,
        buildStartAt: daysFromNow(20),
        buildEndAt: DEADLINE_30_DAYS,
        submissionDeadlineAt: DEADLINE_30_DAYS,
        judgingStartAt: daysFromNow(29),
        judgingEndAt: daysFromNow(34),
        demoDayAt: null,
        resultAt: daysFromNow(35),
        format: 'online',
        location: null,
        state: 'registration',
        rulesSourceId: null,
        rulesRetrievedAt: NOW,
        rulesSha256: '1'.repeat(64),
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'cycle:bnb-online',
        opportunityId: 'opportunity:bnb-online',
        cycleName: 'BNB Hack Online',
        registrationOpenAt: NOW,
        registrationCloseAt: DEADLINE_72_HOURS,
        buildStartAt: NOW,
        buildEndAt: DEADLINE_72_HOURS,
        submissionDeadlineAt: DEADLINE_72_HOURS,
        judgingStartAt: daysFromNow(3),
        judgingEndAt: daysFromNow(6),
        demoDayAt: null,
        resultAt: daysFromNow(7),
        format: 'online',
        location: null,
        state: 'building',
        rulesSourceId: null,
        rulesRetrievedAt: NOW,
        rulesSha256: '2'.repeat(64),
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'cycle:agentic-cinema',
        opportunityId: 'opportunity:agentic-cinema',
        cycleName: 'Agentic Cinema',
        registrationOpenAt: NOW,
        registrationCloseAt: DEADLINE_14_DAYS,
        buildStartAt: NOW,
        buildEndAt: DEADLINE_14_DAYS,
        submissionDeadlineAt: DEADLINE_14_DAYS,
        judgingStartAt: daysFromNow(11),
        judgingEndAt: daysFromNow(14),
        demoDayAt: null,
        resultAt: daysFromNow(15),
        format: 'online',
        location: null,
        state: 'building',
        rulesSourceId: null,
        rulesRetrievedAt: NOW,
        rulesSha256: '3'.repeat(64),
        createdAt: NOW,
        updatedAt: NOW,
      },
      {
        id: 'cycle:colosseum-eternal',
        opportunityId: 'opportunity:colosseum-eternal',
        cycleName: 'Colosseum Eternal',
        registrationOpenAt: null,
        registrationCloseAt: null,
        buildStartAt: null,
        buildEndAt: null,
        submissionDeadlineAt: null,
        judgingStartAt: null,
        judgingEndAt: null,
        demoDayAt: null,
        resultAt: null,
        format: 'online',
        location: null,
        state: 'watchlist',
        rulesSourceId: null,
        rulesRetrievedAt: NOW,
        rulesSha256: '4'.repeat(64),
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    hackathonEntries: [
      {
        id: 'entry:alice-operator',
        cycleId: 'cycle:ethglobal-agentic',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'Alice governed MCP operator for a bounded community workflow.',
        userOutcome: 'A community lead finishes a recurring support workflow with a complete trace.',
        ecosystemAdapter: 'Ethereum attestation adapter.',
        estimatedHours: 28,
        reusePercentage: 82,
        strategicFit: 9,
        acceptanceProbability: 7,
        capitalUpside: 7,
        distributionUpside: 9,
        technicalLeverage: 9,
        credibility: 8,
        urgency: 7,
        effortEfficiency: 8,
        lockInSafety: 9,
        weightedScore: 85,
        founderDecision: 'go',
        founderRationale: 'High reuse and high distribution value.',
        state: 'building',
        createdAt: NOW,
        updatedAt: NOW,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: DEADLINE_30_DAYS,
      },
      {
        id: 'entry:sw4p-settlement',
        cycleId: 'cycle:ethglobal-agentic',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'SW4P programmable creator settlement.',
        userOutcome: 'A creator receives a fee-correct, gas-aware payout with proof.',
        ecosystemAdapter: 'Ethereum settlement adapter.',
        estimatedHours: 44,
        reusePercentage: 65,
        strategicFit: 8,
        acceptanceProbability: 6,
        capitalUpside: 8,
        distributionUpside: 7,
        technicalLeverage: 8,
        credibility: 7,
        urgency: 6,
        effortEfficiency: 5,
        lockInSafety: 8,
        weightedScore: 72,
        founderDecision: 'pending',
        founderRationale: null,
        state: 'candidate',
        createdAt: NOW,
        updatedAt: NOW,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'uncertain',
        nextDeadlineAt: DEADLINE_30_DAYS,
      },
    ],
    hackathonPortfolio: {
      openUpcomingRollingCycles: 4,
      candidateEntries: 1,
      approvedActiveBuilds: 1,
      submissionReadyEntries: 0,
      submittedEntries: 0,
      finalistsWins: 0,
      nextDeadlineAt: DEADLINE_72_HOURS,
      blockedEntries: 1,
      estimatedActiveHours: 28,
    },
  };
}
