import type { StudioAppBootstrap } from '../../src/shared/hackathon-contracts';
import { bootstrapFixture } from './fixtures';

const NOW = '2026-08-15T12:00:00.000Z';
const DEADLINE = '2026-09-12T23:59:00.000Z';

export function hackathonBootstrapFixture(): StudioAppBootstrap {
  const founder = bootstrapFixture();
  const hackathonNarrative = {
    ...founder.narrativeProfiles.find((item) => item.id === 'narrative:test:draft')!,
    id: 'narrative:test:hackathon',
    approvalState: 'approved' as const,
    contentSha256: 'f'.repeat(64),
    approvedAt: NOW,
  };

  return {
    ...founder,
    narrativeProfiles: [...founder.narrativeProfiles, hackathonNarrative],
    organizations: [
      {
        id: 'organization:ethglobal',
        name: 'ETHGlobal',
        normalizedName: 'ethglobal',
        kind: 'protocol',
        website: 'https://ethglobal.com',
        description: 'Ethereum developer events and hackathons.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    opportunities: [
      {
        id: 'opportunity:ethglobal-agentic',
        organizerOrganizationId: 'organization:ethglobal',
        name: 'ETHGlobal Agentic Ethereum',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://ethglobal.com/events',
        applicationUrl: 'https://ethglobal.com/events',
        openDate: '2026-08-01',
        deadline: '2026-09-12',
        startDate: '2026-09-04',
        endDate: '2026-09-12',
        format: 'online',
        location: null,
        eligibilitySummary: 'Open online build competition.',
        termsSummary: 'Use sponsor technology honestly and disclose prior work.',
        capitalPrizeSummary: 'Sponsor bounties and ecosystem follow-on opportunities.',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    hackathonCycles: [
      {
        id: 'cycle:ethglobal-agentic',
        opportunityId: 'opportunity:ethglobal-agentic',
        cycleName: 'ETHGlobal Agentic Ethereum 2026',
        registrationOpenAt: '2026-08-01T00:00:00.000Z',
        registrationCloseAt: DEADLINE,
        buildStartAt: '2026-09-04T00:00:00.000Z',
        buildEndAt: DEADLINE,
        submissionDeadlineAt: DEADLINE,
        judgingStartAt: '2026-09-13T00:00:00.000Z',
        judgingEndAt: '2026-09-18T00:00:00.000Z',
        demoDayAt: null,
        resultAt: '2026-09-19T00:00:00.000Z',
        format: 'online',
        location: null,
        state: 'registration',
        rulesSourceId: null,
        rulesRetrievedAt: NOW,
        rulesSha256: '1'.repeat(64),
        createdAt: NOW,
        updatedAt: NOW,
      },
    ],
    hackathonEntries: [
      {
        id: 'entry:alice-operator',
        cycleId: 'cycle:ethglobal-agentic',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'Alice governed MCP operator for a bounded community workflow.',
        userOutcome: 'A community lead finishes a recurring support workflow with a complete trace.',
        ecosystemAdapter: 'Ethereum attestation adapter.',
        estimatedHours: 28,
        reusePercentage: 82,
        strategicFit: 9,
        acceptanceProbability: 7,
        capitalUpside: 7,
        distributionUpside: 9,
        technicalLeverage: 9,
        credibility: 8,
        urgency: 7,
        effortEfficiency: 8,
        lockInSafety: 9,
        weightedScore: 85,
        founderDecision: 'go',
        founderRationale: 'High reuse and high distribution value.',
        state: 'building',
        createdAt: NOW,
        updatedAt: NOW,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: DEADLINE,
      },
      {
        id: 'entry:sw4p-settlement',
        cycleId: 'cycle:ethglobal-agentic',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'SW4P programmable creator settlement.',
        userOutcome: 'A creator receives a fee-correct, gas-aware payout with proof.',
        ecosystemAdapter: 'Ethereum settlement adapter.',
        estimatedHours: 44,
        reusePercentage: 65,
        strategicFit: 8,
        acceptanceProbability: 6,
        capitalUpside: 8,
        distributionUpside: 7,
        technicalLeverage: 8,
        credibility: 7,
        urgency: 6,
        effortEfficiency: 5,
        lockInSafety: 8,
        weightedScore: 72,
        founderDecision: 'pending',
        founderRationale: null,
        state: 'candidate',
        createdAt: NOW,
        updatedAt: NOW,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'uncertain',
        nextDeadlineAt: DEADLINE,
      },
    ],
    hackathonPortfolio: {
      openUpcomingRollingCycles: 1,
      candidateEntries: 1,
      approvedActiveBuilds: 1,
      submissionReadyEntries: 0,
      submittedEntries: 0,
      finalistsWins: 0,
      nextDeadlineAt: DEADLINE,
      blockedEntries: 1,
      estimatedActiveHours: 28,
    },
  };
}
