import type { StudioAppBootstrap } from '../../src/shared/hackathon-contracts';
import { bootstrapFixture } from './fixtures';

const NOW = new Date();

function future(hours: number): string {
  return new Date(NOW.valueOf() + hours * 60 * 60 * 1_000).toISOString();
}

function datePart(value: string): string {
  return value.slice(0, 10);
}

export function hackathonStudioFixture(): StudioAppBootstrap {
  const base = bootstrapFixture() as StudioAppBootstrap;
  base.narrativeProfiles.push({
    id: 'narrative:test:hackathon:2',
    legalEntityId: 'legal-entity:test',
    ventureId: 'venture:test',
    purpose: 'hackathon',
    version: 2,
    approvalState: 'approved',
    contentSha256: 'f'.repeat(64),
    approvedAt: NOW.toISOString(),
    descriptions: {
      words50: 'Local Labs enters one governed agent workflow.',
      words100: 'Local Labs demonstrates one bounded agent workflow with founder approval.',
      words250:
        'Local Labs demonstrates one bounded agent workflow with selected tools, founder approval, evidence and a reusable distribution program.',
    },
    problem: 'Hackathon teams rebuild operating and distribution work from scratch.',
    productWedge: 'One reusable demo becomes one bounded ecosystem launch.',
    whyNow: 'Agent tools and ecosystem programs are converging.',
    technicalDifferentiation: 'Authority, evidence, build state and distribution stay connected.',
    evidenceFraming: 'Use reproducible commits, tests and receipts.',
    businessModel: 'Infrastructure and partner programs.',
    useOfFunds: 'Ship adapters and convert ecosystem relationships.',
    claimsBoundary: 'Do not present planned integrations as completed evidence.',
    deckReference: null,
    demoReference: null,
  });

  const deadline72 = future(48);
  const deadline14 = future(9 * 24);
  const deadline30 = future(24 * 24);
  const timestamp = NOW.toISOString();

  return {
    ...base,
    organizations: [
      {
        id: 'organization:ecosystem',
        name: 'Example Ecosystem',
        normalizedName: 'example ecosystem',
        kind: 'foundation',
        website: 'https://ecosystem.example',
        description: 'Runs developer and startup programs.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    opportunities: [
      {
        id: 'opportunity:urgent',
        organizerOrganizationId: 'organization:ecosystem',
        name: 'Example Agent Hackathon',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://ecosystem.example/agent-hackathon',
        applicationUrl: null,
        openDate: datePart(timestamp),
        deadline: datePart(deadline72),
        startDate: datePart(timestamp),
        endDate: datePart(deadline72),
        format: 'online',
        location: null,
        eligibilitySummary: 'Existing code is permitted.',
        termsSummary: null,
        capitalPrizeSummary: '$100,000 prize pool',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'opportunity:active',
        organizerOrganizationId: 'organization:ecosystem',
        name: 'Example Stablecoin Challenge',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://ecosystem.example/stablecoin',
        applicationUrl: null,
        openDate: datePart(timestamp),
        deadline: datePart(deadline14),
        startDate: datePart(timestamp),
        endDate: datePart(deadline14),
        format: 'hybrid',
        location: 'New York, NY',
        eligibilitySummary: 'Global teams may participate online.',
        termsSummary: null,
        capitalPrizeSummary: '$50,000 prize pool',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'opportunity:watch',
        organizerOrganizationId: 'organization:ecosystem',
        name: 'Example Media Lab',
        opportunityType: 'hackathon',
        status: 'watchlist',
        publicUrl: 'https://ecosystem.example/media',
        applicationUrl: null,
        openDate: null,
        deadline: datePart(deadline30),
        startDate: null,
        endDate: null,
        format: 'in_person',
        location: 'London, UK',
        eligibilitySummary: null,
        termsSummary: null,
        capitalPrizeSummary: null,
        freshnessState: 'aging',
        reviewState: 'pending',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    hackathonCycles: [
      {
        id: 'cycle:urgent',
        opportunityId: 'opportunity:urgent',
        cycleName: 'Agent Hackathon 2026',
        registrationOpenAt: timestamp,
        registrationCloseAt: null,
        buildStartAt: timestamp,
        buildEndAt: deadline72,
        submissionDeadlineAt: deadline72,
        judgingStartAt: null,
        judgingEndAt: null,
        demoDayAt: null,
        resultAt: null,
        format: 'online',
        location: null,
        state: 'building',
        rulesSourceId: 'source:rules',
        rulesRetrievedAt: timestamp,
        rulesSha256: '1'.repeat(64),
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'cycle:active',
        opportunityId: 'opportunity:active',
        cycleName: 'Stablecoin Challenge 2026',
        registrationOpenAt: timestamp,
        registrationCloseAt: null,
        buildStartAt: timestamp,
        buildEndAt: deadline14,
        submissionDeadlineAt: deadline14,
        judgingStartAt: null,
        judgingEndAt: null,
        demoDayAt: null,
        resultAt: null,
        format: 'hybrid',
        location: 'New York, NY',
        state: 'building',
        rulesSourceId: 'source:rules',
        rulesRetrievedAt: timestamp,
        rulesSha256: '2'.repeat(64),
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'cycle:watch',
        opportunityId: 'opportunity:watch',
        cycleName: 'Media Lab watchlist',
        registrationOpenAt: null,
        registrationCloseAt: null,
        buildStartAt: null,
        buildEndAt: null,
        submissionDeadlineAt: deadline30,
        judgingStartAt: null,
        judgingEndAt: null,
        demoDayAt: null,
        resultAt: null,
        format: 'in_person',
        location: 'London, UK',
        state: 'watchlist',
        rulesSourceId: null,
        rulesRetrievedAt: null,
        rulesSha256: null,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    hackathonEntries: [
      {
        id: 'entry:urgent',
        cycleId: 'cycle:urgent',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon:2',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'A governed agent operator for ecosystem support.',
        userOutcome: 'A founder completes one bounded support workflow.',
        ecosystemAdapter: 'Example Ecosystem tool adapter.',
        estimatedHours: 48,
        reusePercentage: 80,
        strategicFit: 9,
        acceptanceProbability: 7,
        capitalUpside: 8,
        distributionUpside: 9,
        technicalLeverage: 9,
        credibility: 8,
        urgency: 9,
        effortEfficiency: 8,
        lockInSafety: 8,
        weightedScore: 85,
        founderDecision: 'pending',
        founderRationale: null,
        state: 'candidate',
        createdAt: timestamp,
        updatedAt: timestamp,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: deadline72,
      },
      {
        id: 'entry:active',
        cycleId: 'cycle:active',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon:2',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'A source-aware creator payout workflow.',
        userOutcome: 'A creator receives the intended stablecoin amount.',
        ecosystemAdapter: 'Example stablecoin adapter.',
        estimatedHours: 36,
        reusePercentage: 72,
        strategicFit: 8,
        acceptanceProbability: 7,
        capitalUpside: 7,
        distributionUpside: 8,
        technicalLeverage: 8,
        credibility: 8,
        urgency: 7,
        effortEfficiency: 8,
        lockInSafety: 7,
        weightedScore: 78,
        founderDecision: 'go',
        founderRationale: 'Strong reusable settlement and distribution path.',
        state: 'building',
        createdAt: timestamp,
        updatedAt: timestamp,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: deadline14,
      },
      {
        id: 'entry:submitted',
        cycleId: 'cycle:active',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:test:hackathon:2',
        canonicalDemoVersionId: 'demo-version:test:2',
        submissionConcept: 'A submitted human-and-agent studio workflow.',
        userOutcome: 'A sponsor brief becomes a live and playable experience.',
        ecosystemAdapter: 'Example media adapter.',
        estimatedHours: 24,
        reusePercentage: 75,
        strategicFit: 8,
        acceptanceProbability: 6,
        capitalUpside: 7,
        distributionUpside: 9,
        technicalLeverage: 7,
        credibility: 8,
        urgency: 5,
        effortEfficiency: 8,
        lockInSafety: 8,
        weightedScore: 77,
        founderDecision: 'go',
        founderRationale: 'Strong marketing and sponsor upside.',
        state: 'submitted',
        createdAt: timestamp,
        updatedAt: timestamp,
        leadVentureId: 'venture:test',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: deadline14,
      },
    ],
    hackathonPortfolio: {
      openUpcomingRollingCycles: 3,
      candidateEntries: 1,
      approvedActiveBuilds: 1,
      submissionReadyEntries: 0,
      submittedEntries: 1,
      finalistsWins: 0,
      nextDeadlineAt: deadline72,
      blockedEntries: 1,
      estimatedActiveHours: 36,
    },
  };
}
