import type { StudioAppBootstrap } from '../../src/shared/hackathon-contracts';
import { bootstrapFixture } from './fixtures';

function futureInstant(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1_000).toISOString();
}

export function hackathonStudioFixture(): StudioAppBootstrap {
  const base = bootstrapFixture();
  const approvedAt = '2026-08-15T12:00:00.000Z';
  return {
    ...base,
    ventures: [
      ...base.ventures,
      {
        id: 'venture:sw4p',
        legalEntityId: 'legal-entity:test',
        name: 'SW4P',
        category: 'Programmable internet-native settlement',
        utility: 'Turns one settlement instruction into a gas-aware, provable outcome.',
        stage: 'pre_production',
        status: 'active',
        publicUrl: null,
        defaultNarrativeProfileId: 'narrative:sw4p:hackathon:1',
        currentDemoVersionId: 'demo-version:sw4p:1',
      },
      {
        id: 'venture:alice',
        legalEntityId: 'legal-entity:test',
        name: 'Alice',
        category: 'Governed agents',
        utility: 'Completes bounded work through approved tools and founder review.',
        stage: 'pre_production',
        status: 'active',
        publicUrl: null,
        defaultNarrativeProfileId: 'narrative:alice:hackathon:1',
        currentDemoVersionId: 'demo-version:alice:1',
      },
    ],
    narrativeProfiles: [
      ...base.narrativeProfiles,
      {
        id: 'narrative:sw4p:hackathon:1',
        legalEntityId: 'legal-entity:test',
        ventureId: 'venture:sw4p',
        purpose: 'hackathon',
        version: 1,
        approvalState: 'approved',
        contentSha256: 'f'.repeat(64),
        approvedAt,
        descriptions: {
          words50: 'SW4P is programmable settlement for applications.',
          words100: 'SW4P executes a bounded payment instruction with fees, proof and reconciliation.',
          words250: 'SW4P demonstrates one programmable settlement outcome with explicit gas, fee, finality and evidence handling.',
        },
        problem: 'Applications repeatedly rebuild payment operations.',
        productWedge: 'One instruction produces a reconciled settlement outcome.',
        whyNow: 'Stablecoins and agent-operated applications need reliable settlement.',
        technicalDifferentiation: 'EVM and Solana execution with proof and reconciliation.',
        evidenceFraming: 'Show the instruction, finality and receipt.',
        businessModel: 'Application settlement fees.',
        useOfFunds: 'Harden adapters and design-partner delivery.',
        claimsBoundary: 'Do not present unbound rails as current production support.',
        deckReference: null,
        demoReference: null,
      },
      {
        id: 'narrative:alice:hackathon:1',
        legalEntityId: 'legal-entity:test',
        ventureId: 'venture:alice',
        purpose: 'hackathon',
        version: 1,
        approvalState: 'approved',
        contentSha256: '1'.repeat(64),
        approvedAt,
        descriptions: {
          words50: 'Alice is a governed operator for bounded work.',
          words100: 'Alice receives a bounded goal, uses approved tools and returns a complete trace.',
          words250: 'Alice demonstrates governed agent execution with explicit authority, approvals, budgets, evidence and recovery.',
        },
        problem: 'Agent workflows lack clear operating authority.',
        productWedge: 'A useful operator with founder-controlled external actions.',
        whyNow: 'Tool-using agents are entering real workflows.',
        technicalDifferentiation: 'Bounded program envelopes, tool policy and durable trace.',
        evidenceFraming: 'Show approval, tool execution and result evidence.',
        businessModel: 'White-label agent deployments and infrastructure.',
        useOfFunds: 'Product hardening and pilot delivery.',
        claimsBoundary: 'Do not imply unattended external authority.',
        deckReference: null,
        demoReference: null,
      },
    ],
    canonicalDemos: [
      ...base.canonicalDemos,
      {
        id: 'demo:sw4p',
        name: 'SW4P Programmable Settlement',
        category: 'Payments / Stablecoins',
        status: 'active',
        versions: [
          {
            id: 'demo-version:sw4p:1',
            demoId: 'demo:sw4p',
            version: 1,
            baselineRepository: 'rndrntwrk/sw4p-docs',
            baselineCommitSha: '2'.repeat(40),
            branchConvention: 'hackathon/{event}/sw4p-settlement',
            expectedBaselineHours: 24,
            coreAssets: ['settlement instruction', 'receipt'],
            evidenceRequirements: ['finality proof', 'reconciliation'],
            approvedClaims: ['The demo produces a reconciled settlement outcome.'],
            contentSha256: '2'.repeat(64),
            approvalState: 'approved',
            approvedAt,
          },
        ],
      },
      {
        id: 'demo:alice',
        name: 'Alice Governed Operator',
        category: 'AI Agents / Developer Infrastructure',
        status: 'active',
        versions: [
          {
            id: 'demo-version:alice:1',
            demoId: 'demo:alice',
            version: 1,
            baselineRepository: 'rndrntwrk/milaidy',
            baselineCommitSha: '3'.repeat(40),
            branchConvention: 'hackathon/{event}/alice-operator',
            expectedBaselineHours: 28,
            coreAssets: ['program envelope', 'approved tools'],
            evidenceRequirements: ['approval trace', 'result artifact'],
            approvedClaims: ['The demo shows a bounded agent using approved tools.'],
            contentSha256: '3'.repeat(64),
            approvalState: 'approved',
            approvedAt,
          },
        ],
      },
    ],
    organizations: [
      {
        id: 'organization:example',
        name: 'Example Foundation',
        normalizedName: 'example foundation',
        kind: 'foundation',
        website: 'https://example.test',
        description: 'A test ecosystem organizer.',
        linkedFirmId: null,
        isPublic: true,
        contributionEligible: false,
        origin: 'local',
        createdAt: approvedAt,
        updatedAt: approvedAt,
      },
    ],
    opportunities: [
      {
        id: 'opportunity:open',
        organizerOrganizationId: 'organization:example',
        name: 'Example Agent and Payments Hackathon',
        opportunityType: 'hackathon',
        status: 'open',
        publicUrl: 'https://example.test/hackathon',
        applicationUrl: null,
        openDate: '2026-08-01',
        deadline: futureInstant(240).slice(0, 10),
        startDate: '2026-08-15',
        endDate: futureInstant(300).slice(0, 10),
        format: 'online',
        location: null,
        eligibilitySummary: 'Reviewed structured rules apply.',
        termsSummary: null,
        capitalPrizeSummary: '$100,000 prize pool',
        freshnessState: 'current',
        reviewState: 'reviewed',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: approvedAt,
        updatedAt: approvedAt,
      },
      {
        id: 'opportunity:watchlist',
        organizerOrganizationId: 'organization:example',
        name: 'Recurring Creator Technology Challenge',
        opportunityType: 'hackathon',
        status: 'watchlist',
        publicUrl: 'https://example.test/watchlist',
        applicationUrl: null,
        openDate: null,
        deadline: null,
        startDate: null,
        endDate: null,
        format: 'hybrid',
        location: null,
        eligibilitySummary: null,
        termsSummary: null,
        capitalPrizeSummary: null,
        freshnessState: 'unknown',
        reviewState: 'pending',
        importedPackageId: null,
        importedPackageDigest: null,
        createdAt: approvedAt,
        updatedAt: approvedAt,
      },
    ],
    hackathonCycles: [
      {
        id: 'cycle:open',
        opportunityId: 'opportunity:open',
        cycleName: '2026 online cycle',
        registrationOpenAt: futureInstant(-24),
        registrationCloseAt: futureInstant(48),
        buildStartAt: futureInstant(72),
        buildEndAt: futureInstant(216),
        submissionDeadlineAt: futureInstant(240),
        judgingStartAt: futureInstant(250),
        judgingEndAt: futureInstant(280),
        demoDayAt: null,
        resultAt: futureInstant(300),
        format: 'online',
        location: null,
        state: 'registration',
        rulesSourceId: 'source:rules',
        rulesRetrievedAt: approvedAt,
        rulesSha256: '4'.repeat(64),
        createdAt: approvedAt,
        updatedAt: approvedAt,
      },
      {
        id: 'cycle:watchlist',
        opportunityId: 'opportunity:watchlist',
        cycleName: 'Next unannounced cycle',
        registrationOpenAt: null,
        registrationCloseAt: null,
        buildStartAt: null,
        buildEndAt: null,
        submissionDeadlineAt: null,
        judgingStartAt: null,
        judgingEndAt: null,
        demoDayAt: null,
        resultAt: null,
        format: 'hybrid',
        location: null,
        state: 'watchlist',
        rulesSourceId: null,
        rulesRetrievedAt: null,
        rulesSha256: null,
        createdAt: approvedAt,
        updatedAt: approvedAt,
      },
    ],
    hackathonEntries: [
      {
        id: 'entry:sw4p',
        cycleId: 'cycle:open',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:sw4p:hackathon:1',
        canonicalDemoVersionId: 'demo-version:sw4p:1',
        submissionConcept: 'SW4P settlement sprint',
        userOutcome: 'A creator receives the intended amount and a reconciled receipt.',
        ecosystemAdapter: 'Example stablecoin SDK',
        estimatedHours: 48,
        reusePercentage: 80,
        strategicFit: 9,
        acceptanceProbability: 7,
        capitalUpside: 8,
        distributionUpside: 9,
        technicalLeverage: 9,
        credibility: 8,
        urgency: 8,
        effortEfficiency: 8,
        lockInSafety: 8,
        weightedScore: 85,
        founderDecision: 'pending',
        founderRationale: null,
        state: 'candidate',
        createdAt: approvedAt,
        updatedAt: approvedAt,
        leadVentureId: 'venture:sw4p',
        eligibilityStatus: 'eligible',
        nextDeadlineAt: futureInstant(240),
      },
      {
        id: 'entry:alice',
        cycleId: 'cycle:open',
        legalEntityId: 'legal-entity:test',
        narrativeProfileId: 'narrative:alice:hackathon:1',
        canonicalDemoVersionId: 'demo-version:alice:1',
        submissionConcept: 'Alice governed operator',
        userOutcome: 'A founder delegates one bounded workflow and receives a complete trace.',
        ecosystemAdapter: 'Example agent-memory service',
        estimatedHours: 36,
        reusePercentage: 72,
        strategicFit: 8,
        acceptanceProbability: 7,
        capitalUpside: 7,
        distributionUpside: 8,
        technicalLeverage: 9,
        credibility: 8,
        urgency: 7,
        effortEfficiency: 8,
        lockInSafety: 8,
        weightedScore: 79.8,
        founderDecision: 'pending',
        founderRationale: null,
        state: 'candidate',
        createdAt: approvedAt,
        updatedAt: approvedAt,
        leadVentureId: 'venture:alice',
        eligibilityStatus: null,
        nextDeadlineAt: futureInstant(240),
      },
    ],
    hackathonPortfolio: {
      openUpcomingRollingCycles: 1,
      candidateEntries: 2,
      approvedActiveBuilds: 0,
      submissionReadyEntries: 0,
      submittedEntries: 0,
      finalistsWins: 0,
      nextDeadlineAt: futureInstant(240),
      blockedEntries: 1,
      estimatedActiveHours: 0,
    },
  };
}
